### ISSUE TITLE
[BUG] Plugin doesn't seems to work properly with crafting quests...

### ISSUE THREAD

**Issue by maxlehot1234** [LMBishop/Quests#117]
Hi,

Is it possible to update Quests for 1.16.x ?
It works, but I got some issue with quests made by someone.
Like if Quests plugin is not able to understand that I got the item in my inventory when the crafting quest has been started.

I need to drop the item that I just craft and take it again to complete the quest which make no sense...

Example quest:
https://gist.github.com/maxlehot1234/d75bd777ca1bc40030f8d4fcb886963a

Let me know if I need to change anything to make it work with PaperMC 1.16.1 build 135.

Thanks again and have a nice day/night

**Comment by FesterHead** [comment]
I have noticed the same issue.  Another workaround is to move anything in the inventory to a different slot.  This will trigger the inventory check task to run.

I think the root cause for this issue is one of the reasons why the code has a `// Still some work to do as it doesn't really work` comment for the InventoryClickEvent trigger.

The inventory check trigger events are:
- [EntityPickupItemEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityPickupItemEvent.html) - Thrown when a entity picks an item up from the ground
- [InventoryClickEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/inventory/InventoryClickEvent.html) - This event is called when a player clicks a slot in an inventory.  

Definitely needs improvement.  Behavior does not seem to be related to the Minecraft version.
