### ISSUE TITLE
Add timestamp in placeholder for completion

### ISSUE THREAD

**Issue by Nesseley** [LMBishop/Quests#382]
### Reason for Addition

Using the placeholder `%quests_quest:{questid}_completiondate%` it gives me the date of completion, I would like to display the timestamp it was completed as well.

### Description of Feature

Maybe something along the lines of `%quests_quest:{questid}_completiontime_GMT+2%` (GMT+2 is my timezone)

using both the completiondate and completiontime placeholder it could look like this:
**25/05/2022 14:31**

### Alternative Solutions

none

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open

**Comment by LMBishop** [comment]
Are you looking for the raw timestamp (i.e. the exact number of milliseconds since 1st January 1970)? Or just to change the way the timestamp is formatted?

The latter question should already be possible (from the wiki):

> **\*\*\*** *the date format may be adjusted by including it at the end: for example `%quests_q:<quest-name>_completiondate_dd/MM HH:mm:ss%` will return a the date of compltion **formatted as `dd/MM HH:mm:ss`** - you may use any letter listed [here](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html)*

So `%quests_quest:{questid}_completiondate_dd/MM/yyyy HH:mm%` should produce an output in the format: 25/05/2022 14:31

**Comment by Nesseley** [comment]
I want to display the time the player completed the quest with a timestamp. I will have a look and see if works! If it does I'l close this :)
