### ISSUE TITLE
Inventory Task option 'remove-items-when-complete' always removes item even when set to false

### ISSUE THREAD

**Issue by ReasonFoundDecoy** [LMBishop/Quests#413]
### Description of Bug

As title says, Inventory Task always removes the item(s) when the task is complete. From the wiki,

`remove-items-when-complete: false     # (OPTIONAL) take the items away from the player on completion - default: false`

it's supposed to default to false. Not having this option under the task removes the item(s), and also having this option under the task and setting it to false still removes the item(s). 

This is the case for any vanilla item, and it's also the case if you use a quest-item as your item.

### Steps to Reproduce

1. Create a quest with task type "inventory"
2. Set it to any vanilla item or any quest-item
3. Set the amount to however many you want
4. Test your quest

and/or

1. Create a quest with task type "inventory"
2. Add option: `remove-items-when-complete: false`
3. Set it to any vanilla item or any quest-item
4. Set the amount to however many you want
5. Test your quest

### Environment

- Minecraft version: 1.19
- Server software: Paper(50) 1.19
- Quests version: 3.13.1

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

### Other

Here are examples of 2 basic quests I've set up for you to test, although you probably have to change the category at the bottom

[admininventorytest1.txt](https://github.com/LMBishop/Quests/files/9106455/admininventorytest1.txt)
[admininventorytest2.txt](https://github.com/LMBishop/Quests/files/9106457/admininventorytest2.txt)

**Comment by LMBishop** [comment]
This is because `allow-partial-completion` is (wrongly) `true` by default, which forces `remove-items-when-complete` to `true` as well. 

I think when I was refactoring all the tasks I, for some reason, changed the default value of `allow-partial-completion` to `true`, and when I was rewriting the documentation I also didn't clock the fact I changed it (probably has something to do with the fact I did most of it at 3 in the morning). This will be changed back to `false` in the next version, for now just set `allow-partial-completion` to `false` manually.
