### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by WolverStones** [LMBishop/Quests#43]
Please add a placeholder such as how many quests the player has already completed etc...

**Comment by MrMorganCz** [comment]
@LMBishop 
Added in version 2.7 


Even one could add a placeholder for the number of completed quests player ..?

**Comment by nicuch** [comment]
Yes, and no. Because the way the quests are saved, I can't really determine how many quests a player has completed.
Now to more technical stuff: a quest is saved for a player by its id. Quests can be repeated, and because of that, when a player repeat a quest, the old quest save is long gone, so I can't keep track to how many quests a player have completed.
It might be a way though; got an idea that just hit me while I'm writing this, but I have to test it.

**Comment by gazdyy** [comment]
when will you add it?

**Comment by gazdyy** [comment]
@nicuch

**Comment by nicuch** [comment]
When I'll have time. I do have a full time job, and also working on other projects.
Plus this one is on low priority.
