### ISSUE TITLE
MySQL support

### ISSUE THREAD

**Issue by Leonardo-DGS** [LMBishop/Quests#50]
Add MySQL support

**Comment by luluxe** [comment]
I really need it do you think it will happen?

**Comment by LMBishop** [comment]
It will happen at some point, however I cannot tell you if any time soon. It's been put off for so long as I don't have very much experience with MySQL (or any other database provider), I currently don't have the time to learn properly, and also the challenges when migrating the current format of Quest progress files over to MySQL due to the amount of data there is per player and how it is currently stored and formatted. If I am going to implement it, I would need to do more research first to do it properly.

**Comment by luluxe** [comment]
Ok thank you for your response

**Comment by owensto** [comment]
https://paste.gg/p/anonymous/00fc8e8d745947dbb97b22f425807a27
https://paste.gg/p/anonymous/d00c60596e1c4e5396d675a7c93d10cb

Issue when trying to load the plugin, on Purpur 1.16.5
