### ISSUE TITLE
Quest progress get deleted when the user disconnects.

### ISSUE THREAD

**Issue by VorteXNation** [LMBishop/Quests#56]
**Description of Error**
When a user starts a quest, let's say, kill 100 Zombies, he kills for example 50, checks his progress and it says 50/100 Zombies, then, he disconnects and connects again, progress will be 0/100 Zombies.

**To Reproduce**
Start a quest that has progress on it, not instant completion like delivering items, make some part of the quest and disconnect, connect again and the quest progress will be deleted.

**Screenshots**
[if you have any screenshots, show them here]

**Server (please complete the following information):**
 - Minecraft Version: 1.14.4
 - Mod Name: PaperSpigot

**Plugin (please complete the following information):**
 - Version: 2.6

**Stacktrace**
No errors.

**Comment by MrPungle** [comment]
I have the same issue,
the playerdata.yml where all the informations are stocked doesn't register the number of zombies you killed (for example), it just register if the quest is completed or not.
So, when user disconnect, the plugin checks what the player have done and save that, then the plugin doesn't save the progression in the quest

**Comment by dellise26** [comment]
Hi there, i'm a co-worker with MrPungle and i just see where the problem is.
When you disconnect your data didn't register but if you look at the data by modifying the code you will see the QplayingManager didn't think the quest is WothRegistring so i look at it and there it is.

The problem is that if you set true the auto enabling setting the quest start but don't register as if it started or should i say the quest-started is set to false, i will look forward to see changes in the few days ( even if its not that tricky ) and you're welcome :)
