### ISSUE TITLE
A problem occured quest progress file is null

### ISSUE THREAD

**Issue by moonies44** [LMBishop/Quests#675]
### Description of Bug

Hello there. when a player logs in i get this error

[22:25:27 INFO]: ScrambleTime joined the game
[22:25:27 INFO]: ScrambleTime[/109.252.118.244:46982] logged in with entity id 126314 at ([world]1463.4168614299595, 177.62657084823462, -572.0126570617338)
[22:25:27 INFO]: [Quests] DEBUG: Loading player 4d6b4af2-53ec-4a5a-9aab-25f4519b5fa4...
[22:25:27 INFO]: [Quests] DEBUG: A problem occurred trying loading player 4d6b4af2-53ec-4a5a-9aab-25f4519b5fa4; quest progress file is null.

### Steps to Reproduce

Login to the server. (they haven't done any quests before)

### Environment

- Minecraft version: 1.20.4 paper
- Server software: paper
- Quests version: 3.15-b636bef

### Agreements

- [X] I am running the latest version of Quests
- [X] I am certain this issue is unique and a similar issue is not currently open
- [X] I am using a version of Minecraft which is supported by Quests

**Comment by Krakenied** [comment]
are you using mysql or files

**Comment by Krakenied** [comment]
also, it's just debug log - maybe it's just phrased in a wrong way, have to take a look into it

**Comment by Krakenied** [comment]
ok i see it returns null only if there is a problem with database connection - ensure your setup is  correct

**Comment by moonies44** [comment]
> ok i see it returns null only if there is a problem with database connection - ensure your setup is correct

thanks for replying, im using flatfile, so im unsure how my setup could be wrong? any other ideas how i can check if something is wrong? thank you.

**Comment by Krakenied** [comment]
Flatfile meaning `provider: "yaml"`, yeah?

**Comment by Krakenied** [comment]
Also, that's only debugging. Do you see any errors without debugging enabled? And, does this thing affect how Quests plugin behaves? From what I can see, this completable future is expected to complete with null due to the nullability checks in the code. So this log is most probably perfectly fine - if you don't encounter any issues, just disable debugging.
https://github.com/LMBishop/Quests/blob/a82c96b60d6a78644d0b74ae4f494a5653d9484d/common/src/main/java/com/leonardobishop/quests/common/player/QPlayerManager.java#L177-L181
https://github.com/LMBishop/Quests/blob/a82c96b60d6a78644d0b74ae4f494a5653d9484d/bukkit/src/main/java/com/leonardobishop/quests/bukkit/util/CommandUtils.java#L133-L136
https://github.com/LMBishop/Quests/blob/a82c96b60d6a78644d0b74ae4f494a5653d9484d/bukkit/src/main/java/com/leonardobishop/quests/bukkit/util/CommandUtils.java#L163-L166
https://github.com/LMBishop/Quests/blob/a82c96b60d6a78644d0b74ae4f494a5653d9484d/bukkit/src/main/java/com/leonardobishop/quests/bukkit/listener/PlayerJoinListener.java#L37-L53
Debug logging can be disabled in config.yml here (as you can see, `2` is default):
https://github.com/LMBishop/Quests/blob/a82c96b60d6a78644d0b74ae4f494a5653d9484d/bukkit/src/main/resources/resources/bukkit/config.yml#L110-L111

**Comment by moonies44** [comment]
ah, it was set to mysql lol, oops. i swear i set it to yaml a while back, think it got reset somehow. i have logged in 3 accounts and have not been able to re-produce the issue. i shall keep an eye on it
