### ISSUE TITLE
Console spamming

### ISSUE THREAD

**Issue by FourNineRugz** [LMBishop/Quests#70]
**Description of Error**
`https://pastebin.com/uMavgcM0`

**To Reproduce**
Not sure entirely.

**Server (please complete the following information):**
 - Minecraft Version: 1.15.1
 - Mod Name: Paper

**Plugin (please complete the following information):**
 - Version: Latest Quests

**Comment by Exillium313** [comment]
I get this all the time, only fixable by force restarting the plugin or in some cases server.

Will get an `[Quests] Task #177 for Quests v2.7 generated an exception`
follow by a NPE and itll spam the console with some type of event.  Often PlayerMoveEvent, sometimes BlockBreakEvent, lately im getting MythicMobsEntityDeath events.

If I didnt have so many quests configured with this plugin I would uninstall it, but I really like how easy it is to make quests and really dont want to go that route.

**Comment by nicuch** [comment]
Needs more investigation as I really can't reproduce any of the errors. Maybe posting a plugin list? It might be the incompability with one or two plugins (that I personally don't have on my live production server, where I also test it) that causes this.

**Comment by Deltawoolf** [comment]
I also get the same error. Since i upgraded my Server on 1.15.2 (we were on 1.13 before) it happens frequently. I have round about 400 Quests and every single one is on autostart. 

My guess is, that the trigger is a faulty QPlayer object which is null. Every time the player does something, an error gets thrown. 
I just checked my logs on the last 3 times the error happened. Just a few seconds before the first error got thrown, a player on my server is getting kicked, because he logged in from another location. All 3 times, a player "logged" in that way just a few seconds before the error started.

Example (with censored playerdata):
`[14:49:51] [LoginProcessingThread/INFO]: UUID of player PLAYER is UUID
[14:49:51] [Server thread/INFO]: PLAYER lost connection: You logged in from another location
[14:49:51] [Server thread/INFO]: [-] PLAYER 
[14:49:52] [Server thread/INFO]: PLAYER [IP-ADRESS] logged in with entity id 255917 at ([ASkyBlock]-18970.683798207585, 114.02188748260286, 3984.5162997703715)
[14:49:52] [Server thread/WARN]: handleDisconnection() called twice
[14:49:55] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Quests [...]`

Im 90% sure that the 1 Tick delay from the Runnable in the EventPlayerLeave Class is causing the error. The player quits and joins the Server at the same time. 1 Tick later, the Runnable removes the playerdata. That causes the null-error wave. I think a check if the Player is online in the runnable that removes the playerdata should fix that problem.

**Comment by nicuch** [comment]
Based on the code, it shouldn't happen even if the player is quiting, because there is offline support (the data for qPlayer is loaded again just for that). I'll have to test it tho. I'm gonna replace the Map<UUID, qPlayer> with ConcurrentMap<UUID, qPlayer> just to be sure its happen-before.

**Comment by nicuch** [comment]
Please try this version: https://github.com/nicuch/Quests-1/releases/tag/2.8-Alpha
You can see the changes here: https://github.com/nicuch/Quests-1/commit/8430035d2f9f8876981bda0e4fc57ae870ddc29d
Please report if any errors shows up.

**Comment by Deltawoolf** [comment]
Thanks for the quick response. 
The errors still appear. I tried it on my test server (1.15.2, paper-79) with only quests installed. 

It's pretty easy to reproduce the bug, just open two instances of Minecraft with the same account. Join with the first instance and then join with the second instance (the first one gets kicked). Then your "account" is bugged and the errors will appear, if you do something. After relogging everything is fine. 

I tried that on v2.7 (just to be sure) and v2.8-Alpha. 
I still suggest to check if the player is online (in the runnable) before removing him out of the map. That did work out for me.

**Comment by nicuch** [comment]
The player is removed when disconnecting (after 1 tick). I see why now it happens. I'll see what can I do.

**Comment by nicuch** [comment]
Please try this version: https://github.com/nicuch/Quests-1/releases/tag/2.8-Alpha
You can see the changes here: https://github.com/nicuch/Quests-1/commit/a74b41c1b62ac47983bc8e7ef135387bfc796adc
I've removed all the async tasks for loading/removing the data. It shouldn't be a big performance hit (from my 3 minutes testing) as in the past I've added a lot of performance optimizations to the code.
Please report if any errors shows up.

**Comment by Deltawoolf** [comment]
Yup, that Version fixes the error. 
I guess the problem is solved, so I just wanted to thank you for your great and active work on that plugin!
