### ISSUE TITLE
Blockbreakcertain task does not work

### ISSUE THREAD

**Issue by iJosePlay** [LMBishop/Quests#96]
**Description of Error**:
Blockbreakcertain task does not work with drops2inv option of AutoSell plugin

**To Reproduce**:
I chose a mission with this task to do it, but when mining the progress bar did not advance

**Server**:
Minecraft Version: 1.8.8
Mod Name: PaperSpigot 1.8.8

**Plugin:**
Version: Quests 2.9.4

**Stacktrace**:
none

**Comment by LMBishop** [comment]
labelled enchancement as i believe this is more due to the implementation of the drops plugin rather than Quests

**Comment by maxlehot1234** [comment]
@iJosePlay 
Test with the latest version on the Autosell (Clip) server.
He fix it yesterday

Also make sure to set block_listener_priority: HIGHEST in AUtosell config.yml and restart the server
It work like a charm for me since yesterday night.

You will probably need to update to latest Spigot/PaperMC version to make it work. Test it with 1.8.8 before but if it wont work, you will need to update your server


@LMBishop I think this can be close, since It work for me using latest Autosell version. You can wait the ticket owner reply before too ;)

**Comment by iJosePlay** [comment]
> @iJosePlay
> Test with the latest version on the Autosell (Clip) server.
> He fix it yesterday
> 
> Also make sure to set block_listener_priority: HIGHEST in AUtosell config.yml and restart the server
> It work like a charm for me since yesterday night.
> 
> You will probably need to update to latest Spigot/PaperMC version to make it work. Test it with 1.8.8 before but if it wont work, you will need to update your server
> 
> @LMBishop I think this can be close, since It work for me using latest Autosell version. You can wait the ticket owner reply before too ;)

Hello, block_listener priority comes like this by default.
Unfortunately the higher versions of the plugin do not have support for 1.8.8
